# Generated by Django 4.0.10 on 2023-06-06 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0008_alter_medicalrecordrequest_request_date'),
        ('healthcenter_admin', '0002_alter_admin_information_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operationhour',
            unique_together={('healthcenter', 'day')},
        ),
    ]
