# Generated by Django 4.0.10 on 2023-06-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_chatmessages_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessages',
            name='notified',
        ),
    ]
