# Generated by Django 4.0.10 on 2023-06-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0003_remove_chatmessages_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
