# Generated by Django 4.0.10 on 2023-05-18 17:52

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthcenter', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryManager',
            fields=[
                ('inventorymanager_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('featured_image', models.ImageField(blank=True, default='pharmacist/user-default.png', null=True, upload_to='doctors/')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=12, null=True)),
                ('health_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthcenter.healthcenter_information')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventorymanager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalEquipment',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('model_number', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('subcategory', models.CharField(blank=True, choices=[('diagnostic', 'Diagnostic Equipments'), ('monitoring', 'Monitoring Equipments'), ('surgical', 'Surgical Instruments'), ('imaging', 'Medical Imaging Equipment'), ('rehabilitation', 'Rehabilitation and Mobility Aids')], max_length=200, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_purchase', models.DateField()),
                ('warranty', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 5, 18))])),
                ('featured_image', models.ImageField(blank=True, default='medicines/Medical Equipment.png', null=True, upload_to='medicines/')),
                ('health_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthcenter.healthcenter_information')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalSupply',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('subcategory', models.CharField(blank=True, choices=[('ppe', 'Personal Protective Equipments (PPEs)'), ('consumables', 'Medical Consumables'), ('wound_care', 'Wound Care Supplies'), ('surgical', 'Surgical Supplies'), ('diagnostic', 'Diagnostic Test Kits')], max_length=200, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('expiration_date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 5, 18))])),
                ('description', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, default='medicines/Medical Supply.png', null=True, upload_to='medicines/')),
                ('health_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthcenter.healthcenter_information')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.CharField(blank=True, max_length=200, null=True)),
                ('featured_image', models.ImageField(blank=True, default='medicines/Medicine.png', null=True, upload_to='medicines/')),
                ('description', models.TextField(blank=True, null=True)),
                ('medicine_type', models.CharField(blank=True, choices=[('tablets', 'tablets'), ('syrup', 'syrup'), ('capsule', 'capsule'), ('general', 'general')], max_length=200, null=True)),
                ('medicine_category', models.CharField(blank=True, choices=[('fever', 'fever'), ('pain', 'pain'), ('cough', 'cough'), ('cold', 'cold'), ('flu', 'flu'), ('diabetes', 'diabetes'), ('eye', 'eye'), ('ear', 'ear'), ('allergy', 'allergy'), ('asthma', 'asthma'), ('bloodpressure', 'bloodpressure'), ('heartdisease', 'heartdisease'), ('vitamins', 'vitamins'), ('digestivehealth', 'digestivehealth'), ('skin', 'skin'), ('infection', 'infection'), ('nurological', 'nurological')], max_length=200, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('expiration_date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 5, 18))])),
                ('health_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthcenter.healthcenter_information')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorymanager')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalSupplyAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorymanager')),
                ('medicalsupply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicalsupply')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalEquipmentAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorymanager')),
                ('medicalequipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicalequipment')),
            ],
        ),
    ]
