# Generated by Django 4.0.10 on 2023-05-19 06:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymanager',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='inventorymanager',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalequipment',
            name='warranty',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 5, 19))]),
        ),
        migrations.AlterField(
            model_name='medicalsupply',
            name='expiration_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 5, 19))]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiration_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 5, 19))]),
        ),
    ]
