# Generated by Django 4.0.10 on 2023-05-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventorymanager_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymanager',
            name='dob',
        ),
        migrations.AddField(
            model_name='inventorymanager',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
