# Generated by Django 4.0.10 on 2023-05-20 09:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventorymanager_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipment',
            name='warranty',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 5, 20))]),
        ),
        migrations.AlterField(
            model_name='medicalsupply',
            name='expiration_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 5, 20))]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiration_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 5, 20))]),
        ),
    ]
