# Generated by Django 4.0.10 on 2023-06-23 08:22
# Generated by Django 4.0.10 on 2023-06-22 02:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_medicalequipment_warranty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipment',
            name='warranty',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 6, 23))]),
        ),
        migrations.AlterField(
            model_name='medicalsupply',
            name='expiration_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 6, 23))]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiration_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 6, 23))]),
        ),
    ]
