# Generated by Django 4.0.10 on 2023-06-24 23:36

import datetime
import django.core.validators
from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_medicalequipment_warranty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalequipment',
            name='dor',
            field=models.DateField(default='2023-06-24', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 6, 24))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='receivedby',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='sponsoredby',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='tor',
            field=models.TimeField(default=datetime.time(23, 35, 15, 461107), validators=[inventory.models.validate_time_not_in_future]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalsupply',
            name='dor',
            field=models.DateField(default='2023-06-24', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 6, 24))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalsupply',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicalsupply',
            name='receivedby',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicalsupply',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicalsupply',
            name='sponsoredby',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicalsupply',
            name='tor',
            field=models.TimeField(default=datetime.time(23, 35, 52, 765275), validators=[inventory.models.validate_time_not_in_future]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='dor',
            field=models.DateField(default='2023-06-24', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 6, 24))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='receivedby',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='sponsoredby',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='tor',
            field=models.TimeField(default=datetime.time(23, 36, 24, 605053), validators=[inventory.models.validate_time_not_in_future]),
            preserve_default=False,
        ),
    ]
