# Generated by Django 4.0.10 on 2023-06-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_medicalequipment_dor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineadjustment',
            name='sponsored_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
