# Generated by Django 4.0.10 on 2023-06-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_medicineadjustment_sponsored_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineadjustment',
            name='modified_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
