# Generated by Django 4.0.10 on 2023-06-29 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_medicineadjustment_modified_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineadjustment',
            name='modified_quantity',
        ),
    ]
