# Generated by Django 4.0.10 on 2023-06-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_medicineadjustment_modified_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalequipmentadjustment',
            name='sponsored_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
