# Generated by Django 4.0.10 on 2025-07-22 07:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_medicalequipment_dor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipment',
            name='dor',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 7, 22))]),
        ),
        migrations.AlterField(
            model_name='medicalequipment',
            name='warranty',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 7, 22))]),
        ),
        migrations.AlterField(
            model_name='medicalsupply',
            name='dor',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 7, 22))]),
        ),
        migrations.AlterField(
            model_name='medicalsupply',
            name='expiration_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 7, 22))]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dor',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 7, 22))]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiration_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 7, 22))]),
        ),
    ]
