# Generated by Codex on 2026-06-03

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_alter_medicalequipment_dor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipment',
            name='dor',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=django.utils.timezone.localdate)]),
        ),
        migrations.AlterField(
            model_name='medicalequipment',
            name='warranty',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=django.utils.timezone.localdate)]),
        ),
        migrations.AlterField(
            model_name='medicalsupply',
            name='dor',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=django.utils.timezone.localdate)]),
        ),
        migrations.AlterField(
            model_name='medicalsupply',
            name='expiration_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=django.utils.timezone.localdate)]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dor',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=django.utils.timezone.localdate)]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiration_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=django.utils.timezone.localdate)]),
        ),
    ]
