# Generated by Django 4.0.10 on 2023-05-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcenter_information',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
