# Generated by Django 4.0.10 on 2023-05-20 09:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_medicalrecord_appointment_and_more'),
        ('healthcenter', '0002_alter_healthcenter_information_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_of_request', models.TextField()),
                ('request_date', models.DateTimeField(default=datetime.datetime(2023, 5, 20, 17, 7, 45, 123529))),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Denied')], default='P', max_length=1)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.patient')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.medicalrecord')),
            ],
        ),
    ]
