# Generated by Django 4.0.10 on 2023-05-20 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0003_medicalrecordrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 23, 6, 5, 843260)),
        ),
    ]
