# Generated by Django 4.0.10 on 2023-05-20 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0006_alter_medicalrecordrequest_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecordrequest',
            name='date_needed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecordrequest',
            name='supporting_documentation',
            field=models.FileField(blank=True, null=True, upload_to='support_docs/'),
        ),
        migrations.AlterField(
            model_name='medicalrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 1, 23, 26, 183131)),
        ),
    ]
