# Generated by Django 4.0.10 on 2023-06-06 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0007_medicalrecordrequest_date_needed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 8, 15, 34, 826123)),
        ),
    ]
