# Generated by Django 4.0.10 on 2023-06-07 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0010_alter_medicalrecordrequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 20, 51, 45, 907896)),
        ),
    ]
