# Generated by Django 4.0.10 on 2023-06-18 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0013_alter_medicalrecordrequest_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cancellations',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='no_shows',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 18, 38, 5, 15343)),
        ),
    ]
