# Generated by Django 4.0.10 on 2023-06-18 13:24
# Generated by Django 4.0.10 on 2023-06-20 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0014_patient_cancellations_patient_no_shows_and_more'),
        ('healthcenter', '0014_alter_medicalrecordrequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 10, 17, 42, 769385)),
        ),
    ]
