# Generated by Django 4.0.10 on 2023-06-23 08:22
# Generated by Django 4.0.10 on 2023-06-20 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0017_alter_medicalrecordrequest_request_date'),
        ('healthcenter', '0017_patient_father_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 16, 22, 23, 531948)),
        ),
    ]
