# Generated by Django 4.0.10 on 2023-06-20 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0020_remove_patient_father_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 13, 57, 38, 638687)),
        ),
    ]
