# Generated by Django 4.0.10 on 2023-06-24 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0025_patient_barangay_num_patient_birth_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 18, 5, 18, 102236)),
        ),
    ]
