# Generated by Django 4.0.10 on 2023-06-29 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0043_alter_medicalrecordrequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 7, 21, 40, 607507)),
        ),
    ]
