# Generated by Django 4.0.10 on 2023-07-01 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0049_alter_medicalrecordrequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 4, 42, 24, 876516)),
        ),
    ]
