# Generated by Django 4.0.10 on 2023-07-03 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0052_alter_medicalrecordrequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 2, 48, 27, 44047)),
        ),
    ]
