# Generated by Django 4.0.10 on 2023-07-07 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0053_alter_medicalrecordrequest_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='terms_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 16, 43, 50, 630259)),
        ),
    ]
