# Generated by Django 4.0.10 on 2023-07-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0054_patient_terms_confirmed_and_more'),
        ('healthcenter', '0056_alter_medicalrecordrequest_request_date'),
    ]

    operations = [
    ]
