# Generated by Django 4.0.10 on 2023-05-18 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthcenter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Information',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('department', models.CharField(blank=True, choices=[('Cardiologists', 'Cardiologists'), ('Neurologists', 'Neurologists'), ('Pediatricians', 'Pediatricians'), ('Physiatrists', 'Physiatrists'), ('Dermatologists', 'Dermatologists')], max_length=200, null=True)),
                ('featured_image', models.ImageField(blank=True, default='doctors/user-default.png', null=True, upload_to='doctors/')),
                ('certificate_image', models.ImageField(blank=True, default='doctors_certificate/default.png', null=True, upload_to='doctors_certificate/')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('nid', models.CharField(blank=True, max_length=200, null=True)),
                ('visiting_hour', models.CharField(blank=True, max_length=200, null=True)),
                ('report_fee', models.IntegerField(blank=True, null=True)),
                ('dob', models.CharField(blank=True, max_length=200, null=True)),
                ('institute', models.CharField(blank=True, max_length=200, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('completion_year', models.CharField(blank=True, max_length=200, null=True)),
                ('work_place', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('start_year', models.CharField(blank=True, max_length=200, null=True)),
                ('end_year', models.CharField(blank=True, max_length=200, null=True)),
                ('register_status', models.CharField(blank=True, max_length=200, null=True)),
                ('health_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcenter.healthcenter_information')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.CharField(blank=True, max_length=200, null=True)),
                ('medicine_name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.CharField(blank=True, max_length=200, null=True)),
                ('days', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
                ('relation_with_meal', models.CharField(blank=True, max_length=200, null=True)),
                ('medicine_description', models.TextField(blank=True, null=True)),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('test_description', models.TextField(blank=True, null=True)),
                ('extra_information', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_information')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcenter.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('specimen_id', models.CharField(blank=True, max_length=200, null=True)),
                ('specimen_type', models.CharField(blank=True, max_length=200, null=True)),
                ('collection_date', models.CharField(blank=True, max_length=200, null=True)),
                ('receiving_date', models.CharField(blank=True, max_length=200, null=True)),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('referred_value', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_date', models.CharField(blank=True, max_length=200, null=True)),
                ('other_information', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor_information')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthcenter.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Walkin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('walk_in_type', models.CharField(choices=[('consultation', 'Consultation'), ('dental', 'Dental'), ('immunization', 'Immunization'), ('animal_bite_treatment', 'Animal Bite Treatment'), ('tb_prevention_treatment', 'TB Prevention and Treatment'), ('post_partum_newborn', 'Post-Partum/Newborn'), ('covid_vaccination', 'Covid Vaccination'), ('milk_letting', 'Milk Letting'), ('essential_medicines', 'Provision of Essential Medicines'), ('prenatal_checkup', 'Pre-natal Check-up'), ('syphilis_hepatitis_hiv', 'Syphilis/Hepatitis/HIV')], max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('healthcenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcenter.healthcenter_information')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthcenter.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('referred_value', models.CharField(blank=True, max_length=200, null=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.report')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('featured_image', models.ImageField(blank=True, default='doctors/user-default.png', null=True, upload_to='doctors/')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=12, null=True)),
                ('health_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcenter.healthcenter_information')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('specimen_id', models.AutoField(primary_key=True, serialize=False)),
                ('specimen_type', models.CharField(blank=True, max_length=200, null=True)),
                ('collection_date', models.CharField(blank=True, max_length=200, null=True)),
                ('receiving_date', models.CharField(blank=True, max_length=200, null=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.report')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription_test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('test_description', models.TextField(blank=True, null=True)),
                ('test_info_id', models.CharField(blank=True, max_length=200, null=True)),
                ('test_info_price', models.CharField(blank=True, max_length=200, null=True)),
                ('test_info_pay_status', models.CharField(blank=True, max_length=200, null=True)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription_medicine',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('frequency', models.CharField(blank=True, max_length=200, null=True)),
                ('relation_with_meal', models.CharField(blank=True, max_length=200, null=True)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('medical_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField()),
                ('lab_name', models.CharField(max_length=255)),
                ('test_date', models.DateField()),
                ('tests_conducted', models.TextField()),
                ('results_summary', models.TextField()),
                ('blood_pressure', models.CharField(max_length=255)),
                ('heart_rate', models.CharField(max_length=255)),
                ('respiratory_rate', models.CharField(max_length=255)),
                ('temperature', models.CharField(max_length=255)),
                ('physical_examination', models.TextField()),
                ('diagnostic_tests', models.CharField(max_length=255)),
                ('disease_condition', models.CharField(choices=[('AFP', 'Acute Flaccid Paralysis'), ('Diphtheria', 'Diphtheria'), ('Measle', 'Measle'), ('Rubella', 'Rubella'), ('Neonatal Tetanus', 'Neonatal Tetanus'), ('Pertussis', 'Pertussis'), ('Chikugunya', 'Chikugunya'), ('Dengue', 'Dengue'), ('Leptospirosis', 'Leptospirosis'), ('Rabies', 'Rabies'), ('Acute Bloody Diarrhea', 'Acute Bloody Diarrhea'), ('Acute Viral Hepatitis', 'Acute Viral Hepatitis'), ('Hepatitis A', 'Hepatitis A'), ('Cholera', 'Cholera'), ('Rotavirus', 'Rotavirus'), ('Typhoid Fever', 'Typhoid Fever'), ('Acute Meningitis Encephalitis Syndrome', 'Acute Meningitis Encephalitis Syndrome'), ('Influenza-Like Illness', 'Influenza-Like Illness'), ('Meningococcal Disease', 'Meningococcal Disease')], max_length=255)),
                ('severity', models.CharField(max_length=255)),
                ('additional_notes', models.TextField()),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor_information')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcenter.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_place_name', models.CharField(blank=True, max_length=200, null=True)),
                ('from_year', models.CharField(blank=True, max_length=200, null=True)),
                ('to_year', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_information')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('institute', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_completion', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_information')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_information')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthcenter.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consultation'), ('dental', 'Dental'), ('immunization', 'Immunization'), ('animal_bite_treatment', 'Animal Bite Treatment'), ('tb_prevention_treatment', 'TB Prevention and Treatment'), ('post_partum_newborn', 'Post-Partum/Newborn'), ('covid_vaccination', 'Covid Vaccination'), ('milk_letting', 'Milk Letting'), ('essential_medicines', 'Provision of Essential Medicines'), ('prenatal_checkup', 'Pre-natal Check-up'), ('syphilis_hepatitis_hiv', 'Syphilis/Hepatitis/HIV')], max_length=200)),
                ('appointment_status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('healthcenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcenter.healthcenter_information')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthcenter.patient')),
            ],
        ),
       
    ]

