# Generated by Django 4.0.10 on 2023-05-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0002_alter_healthcenter_information_phone_number'),
        ('doctor', '0002_remove_doctor_information_report_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.appointment'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='healthcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcenter.healthcenter_information'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='walkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.walkin'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.appointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='healthcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcenter.healthcenter_information'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='walkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.walkin'),
        ),
    ]
