# Generated by Django 4.0.10 on 2023-05-19 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_medicalrecord_appointment_medicalrecord_healthcenter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='walkin',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='walkin',
        ),
        migrations.AddField(
            model_name='appointment',
            name='medical_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.medicalrecord'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.prescription'),
        ),
        migrations.AddField(
            model_name='walkin',
            name='medical_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.medicalrecord'),
        ),
        migrations.AddField(
            model_name='walkin',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.prescription'),
        ),
    ]
