# Generated by Django 4.0.10 on 2023-05-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_medicalrecord_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='request',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Dental', 'Dental'), ('Immunization', 'Immunization'), ('Animal Bite Treatment', 'Animal Bite Treatment'), ('TB Prevention Treatment', 'TB Prevention and Treatment'), ('Post Partum Newborn', 'Post-Partum/Newborn'), ('Covid Vaccination', 'Covid Vaccination'), ('Milk Letting', 'Milk Letting'), ('Essential Medicines', 'Provision of Essential Medicines'), ('Prenatal Checkup', 'Pre-natal Check-up'), ('Syphilis Hepatitis HIV', 'Syphilis/Hepatitis/HIV')], max_length=200),
        ),
        migrations.AlterField(
            model_name='walkin',
            name='walk_in_type',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Dental', 'Dental'), ('Immunization', 'Immunization'), ('Animal Bite Treatment', 'Animal Bite Treatment'), ('TB Prevention Treatment', 'TB Prevention and Treatment'), ('Post Partum Newborn', 'Post-Partum/Newborn'), ('Covid Vaccination', 'Covid Vaccination'), ('Milk Letting', 'Milk Letting'), ('Essential Medicines', 'Provision of Essential Medicines'), ('Prenatal Checkup', 'Pre-natal Check-up'), ('Syphilis Hepatitis HIV', 'Syphilis/Hepatitis/HIV')], max_length=200),
        ),
    ]
