# Generated by Django 4.0.10 on 2023-05-20 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0005_alter_medicalrecordrequest_request_date'),
        ('doctor', '0006_remove_medicalrecord_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRecordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_of_request', models.TextField()),
                ('request_date', models.DateTimeField(default=datetime.datetime(2023, 5, 21, 0, 43, 4, 295347))),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Denied')], default='P', max_length=1)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_information')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.patient')),
            ],
        ),
    ]
