# Generated by Django 4.0.10 on 2023-05-20 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_doctorrecordrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorrecordrequest',
            name='date_needed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorrecordrequest',
            name='supporting_documentation',
            field=models.FileField(blank=True, null=True, upload_to='support_docs/'),
        ),
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 1, 19, 2, 157123)),
        ),
    ]
