# Generated by Django 4.0.10 on 2023-06-06 00:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0008_alter_medicalrecordrequest_request_date'),
        ('doctor', '0009_alter_doctorrecordrequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 8, 15, 34, 859893)),
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('vaccination_id', models.AutoField(primary_key=True, serialize=False)),
                ('lot_number', models.CharField(blank=True, max_length=200, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('date_given', models.DateField(blank=True, null=True)),
                ('given_by', models.CharField(blank=True, max_length=200, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='healthcenter.patient')),
            ],
        ),
    ]
