# Generated by Django 4.0.10 on 2023-06-06 00:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0009_alter_medicalrecordrequest_request_date'),
        ('doctor', '0010_alter_doctorrecordrequest_request_date_vaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 8, 17, 23, 165022)),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcenter.patient'),
        ),
    ]
