# Generated by Django 4.0.10 on 2023-06-06 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_alter_doctorrecordrequest_request_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='create_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 8, 20, 57, 61074)),
        ),
    ]
