# Generated by Django 4.0.10 on 2023-06-07 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_vaccination_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='dose_number',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third (Booster)'), (4, 'Fourth (Booster)')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccination',
            name='vaccine_name',
            field=models.CharField(choices=[('Pfizer-BioNTech', 'Pfizer-BioNTech'), ('Moderna', 'Moderna'), ('Johnson & Johnson', 'Johnson & Johnson'), ('AstraZeneca', 'AstraZeneca'), ('Covaxin', 'Covaxin'), ('Sinovac', 'Sinovac'), ('Sputnik V', 'Sputnik V')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 20, 51, 45, 939648)),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
