# Generated by Django 4.0.10 on 2023-06-07 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0012_alter_medicalrecordrequest_request_date'),
        ('doctor', '0013_vaccination_dose_number_vaccination_vaccine_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='healthcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcenter.healthcenter_information'),
        ),
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 21, 7, 14, 68698)),
        ),
    ]
