# Generated by Django 4.0.10 on 2023-06-07 19:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_vaccination_healthcenter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.staff'),
        ),
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 3, 28, 6, 312477)),
        ),
    ]
