# Generated by Django 4.0.10 on 2023-06-18 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_vaccination_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 18, 38, 5, 23343)),
        ),
    ]
