# Generated by Django 4.0.10 on 2023-06-20 02:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0014_alter_medicalrecordrequest_request_date'),
        ('doctor', '0015_vaccination_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 10, 2, 9, 373608)),
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('immunization_id', models.AutoField(primary_key=True, serialize=False)),
                ('immune_name', models.CharField(choices=[('BCG', 'BCG'), ('HEPATITIS B', 'HEPATITIS B'), ('PENTAVALENT VACCINE', 'PENTAVALENT VACCINE'), ('ORAL POLIO VACCINE', 'ORAL POLIO VACCINE'), ('INACTIVATED POLIO VACCINE', 'INACTIVATED POLIO VACCINE'), ('PNEUMOCOCCAL CONJUGATE VACCINE', 'PNEUMOCOCCAL CONJUGATE VACCINE'), ('ATTIENUATED MEASLES VACCINE', 'ATTIENUATED MEASLES VACCINE'), ('MEASLES, MUMPS, RUBELLA', 'MEASLES, MUMPS, RUBELLA'), ('Others', 'Others')], max_length=200)),
                ('dose_number', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth')])),
                ('lot_number', models.CharField(blank=True, max_length=200, null=True)),
                ('date_given', models.DateField(blank=True, null=True)),
                ('given_by', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('healthcenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcenter.healthcenter_information')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcenter.patient')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.staff')),
            ],
        ),
    ]
