# Generated by Django 4.0.10 on 2023-06-20 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_alter_doctorrecordrequest_request_date_immunization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 10, 17, 42, 786385)),
        ),
    ]
