# Generated by Django 4.0.10 on 2023-06-18 13:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0015_alter_medicalrecordrequest_request_date'),
        ('doctor', '0016_alter_doctorrecordrequest_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='urgency',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 21, 24, 54, 976889)),
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desired_date', models.DateField(blank=True, null=True)),
                ('desired_time', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('appointment_type', models.CharField(blank=True, choices=[('Consultation', 'Consultation'), ('Dental', 'Dental'), ('Immunization', 'Immunization'), ('Animal Bite Treatment', 'Animal Bite Treatment'), ('TB Prevention Treatment', 'TB Prevention and Treatment'), ('Post Partum Newborn', 'Post-Partum/Newborn'), ('Covid Vaccination', 'Covid Vaccination'), ('Milk Letting', 'Milk Letting'), ('Essential Medicines', 'Provision of Essential Medicines'), ('Prenatal Checkup', 'Pre-natal Check-up'), ('Syphilis Hepatitis HIV', 'Syphilis/Hepatitis/HIV')], max_length=200, null=True)),
                ('healthcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.healthcenter_information')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.patient')),
            ],
        ),
    ]
