# Generated by Django 4.0.10 on 2023-06-20 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_alter_doctorrecordrequest_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='urgency',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 3, 29, 17, 742428)),
        ),
    ]
