# Generated by Django 4.0.10 on 2023-06-20 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_alter_doctorrecordrequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 12, 58, 5, 581682)),
        ),
    ]
