# Generated by Django 4.0.10 on 2023-06-21 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_immunization_barangay_num_immunization_birth_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 21, 52, 46, 283979)),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='dose_number',
            field=models.IntegerField(choices=[(0, 'At birth'), (1, '1st Visit'), (2, '2nd Visit'), (3, '3rd Visit'), (4, '4th Visit'), (5, '5th Visit'), (6, '6th Visit')]),
        ),
    ]
