# Generated by Django 4.0.10 on 2023-06-22 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0024_alter_doctorrecordrequest_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 10, 0, 55, 814171)),
        ),
    ]
