# Generated by Django 4.0.10 on 2023-06-22 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0026_alter_doctorrecordrequest_request_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immunization',
            name='barangay_num',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='birth_height',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='birth_weight',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='fam_num',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='place_birth',
        ),
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 12, 42, 2, 936697)),
        ),
    ]
