# Generated by Django 4.0.10 on 2023-06-24 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_doctor_review_symptoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 18, 36, 40, 717421)),
        ),
    ]
