# Generated by Django 4.0.10 on 2023-06-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_appointment_confirmed_and_more'),
        ('doctor', '0030_alter_doctorrecordrequest_request_date'),
    ]

    operations = [
    ]
