# Generated by Django 4.0.10 on 2023-06-24 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0031_merge_20230625_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 4, 48, 3, 677117)),
        ),
    ]
