# Generated by Django 4.0.10 on 2023-06-28 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0038_alter_doctorrecordrequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 9, 31, 1, 539961)),
        ),
    ]
