# Generated by Django 4.0.10 on 2023-06-28 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0042_alter_doctorrecordrequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 22, 49, 23, 776986)),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='barangay_num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='birth_height',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='birth_weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='fam_num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
