# Generated by Django 4.0.10 on 2023-06-29 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0043_alter_doctorrecordrequest_request_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 18, 32, 37, 97545)),
        ),
    ]
