# Generated by Django 4.0.10 on 2023-06-29 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0044_vaccination_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 18, 52, 35, 459760)),
        ),
    ]
