# Generated by Django 4.0.10 on 2023-06-30 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0051_alter_doctorrecordrequest_request_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immunization',
            name='barangay_num',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='birth_height',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='birth_weight',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='fam_num',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='place_birth',
        ),
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 4, 5, 24, 358320)),
        ),
    ]
