# Generated by Django 4.0.10 on 2023-07-01 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0052_remove_immunization_barangay_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.CharField(blank=True, default='None', max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='symptoms',
            field=models.CharField(blank=True, default='None', max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='walkin',
            name='symptoms',
            field=models.CharField(blank=True, default='None', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 4, 42, 24, 887060)),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='message',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='walkin',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
