# Generated by Django 4.0.10 on 2023-07-02 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0053_appointment_symptoms_waitlist_symptoms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunization',
            name='immune_record',
            field=models.CharField(choices=[('Child', 'Child'), ('Adult', 'Adult')], default='Child', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='immunization',
            name='othervaccine_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='immunization',
            name='visit_number',
            field=models.IntegerField(choices=[(0, 'At Birth'), (1, '1st Visit'), (2, '2nd Visit'), (3, '3rd Visit'), (3, '4th Visit'), (5, '5th Visit'), (6, 'others')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 23, 40, 23, 110359)),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='dose_number',
            field=models.IntegerField(choices=[(1, '1st Dose'), (2, '2nd Dose'), (3, '3rd Dose')]),
        ),
    ]
