# Generated by Django 4.0.10 on 2023-07-03 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0054_immunization_immune_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 14, 31, 9, 561190)),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='dose_number',
            field=models.CharField(choices=[('1st Dose', '1st Dose'), ('2nd Dose', '2nd Dose'), ('3rd Dose', '3rd Dose')], max_length=200),
        ),
    ]
