# Generated by Django 4.0.10 on 2023-07-03 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0055_alter_doctorrecordrequest_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 2, 48, 27, 60169)),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='visit_number',
            field=models.IntegerField(choices=[(0, 'At Birth'), (1, '1st Visit'), (2, '2nd Visit'), (3, '3rd Visit'), (4, '4th Visit'), (5, '5th Visit'), (6, 'others')]),
        ),
    ]
