# Generated by Django 4.0.10 on 2023-07-07 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0056_alter_doctorrecordrequest_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 10, 27, 52, 238710)),
        ),
    ]
