# Generated by Django 4.0.10 on 2023-07-07 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0058_immunization_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecordrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 13, 14, 5, 30728)),
        ),
    ]
