# Generated by Django 4.0.10 on 2024-05-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0062_medicalrecord_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription_test',
            name='test_info_id',
        ),
    ]
